"""add prayer creator fk and indexes

Revision ID: 3113d78baa38
Revises: c1f9cdfa32da
Create Date: 2026-01-02 20:30:46.188868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3113d78baa38'
down_revision: Union[str, Sequence[str], None] = 'c1f9cdfa32da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prayers', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_prayers_created_by'), 'prayers', ['created_by'], unique=False)
    op.create_index('ix_prayers_date_creator', 'prayers', ['prayer_date', 'created_by'], unique=False)
    op.create_index(op.f('ix_prayers_prayer_date'), 'prayers', ['prayer_date'], unique=False)
    op.create_foreign_key('fk_prayers_created_by_users', 'prayers', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_prayers_created_by_users', 'prayers', type_='foreignkey')
    op.drop_index(op.f('ix_prayers_prayer_date'), table_name='prayers')
    op.drop_index('ix_prayers_date_creator', table_name='prayers')
    op.drop_index(op.f('ix_prayers_created_by'), table_name='prayers')
    op.drop_column('prayers', 'created_by')
    # ### end Alembic commands ###
